# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            Eos 314 Descriptive Physical Oceanography
tagline:          'EOS 314: Descriptive Physical Oceanography'
description:      ''
url:              http://jklymak.github.io/Eos314/
baseurl:          '/Eos314'

author:
  name:           'Jody Klymak'
  url:            http://web.uvic.ca/~jklymak

paginate:         5
paginate_path: "blog/page:num"

github:
  repo:           https://github.com/jklymak/Eos314
