# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            Eos 314 Descriptive Physical Oceanography
tagline:          'EOS 314: Descriptive Physical Oceanography'
description:      ''
url:              http://web.uvic.ca/~jklymak/Eos314/
baseurl:          '/~jklymak/Eos314'

author:
  name:           'Jody Klymak'
  url:            http://web.uvic.ca/~jklymak/Eos314

paginate:         5
paginate_path: "blog/page:num"

github:
  repo:           https://github.com/jklymak/Eos314
